[package]
name = "epub-index"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.2"
epub = "2.1.1"
walkdir = "2.3.3"

[[bin]]
name = "epub-index"
path = "main.rs"
